version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

workflows:
  test:
    jobs:
      - bundle_audit
      - rspec

jobs:
  bundle_audit:
    docker:
      - image: cimg/ruby:2.7.1
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install bundler-audit
          command: gem install bundler-audit
      - run:
          name: bundle-audit check
          command: bundle-audit check --update
  rspec:
    docker:
      - image: cimg/ruby:2.7.1
    resource_class: small
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
